spring:
  application:
    name: batchApp
  main:
    allow-bean-definition-overriding: true
  
  # Configuration des bases de données
  datasource:
    # Configuration PostgreSQL (destination)
    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/mydatabase
      username: myuser
      password: mypassword
      driver-class-name: org.postgresql.Driver
      
    # Configuration Trino (source)
    trino:
      jdbc-url: jdbc:trino://localhost:8080/tpch/sf1?SSL=false
      username: tpch
      password:
      driver-class-name: io.trino.jdbc.TrinoDriver
  
  # Configuration Spring Batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false  # Désactivé car nous utilisons notre propre launcer

# Configuration batch
batch:
  # Paramètres généraux
  chunk-size: 5000
  throttle-limit: 4
  max-retries: 3
  
  # Skip policy configuration
  skip-policy:
    enabled: true
    max-skips: 100
    
# Configuration des loggers
logging:
  level:
    root: INFO
    com.ilahouar.batchapp: INFO
    org.springframework.batch: INFO
    
    # Niveau DEBUG pour voir les requêtes SQL
    # org.springframework.jdbc.core.JdbcTemplate: DEBUG
    
    # Niveau TRACE pour les opérations batch détaillées
    # org.springframework.batch.core: DEBUG
    # org.springframework.batch.item: DEBUG 